services:
  - type: web
    name: afar-justice
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://afar-justice.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: afar-justice-db
          property: connectionString

databases:
  - name: afar-justice-db
    plan: free
    databaseName: afar_justice
    user: afar_justice
